# Generated by Django 2.2.5 on 2019-12-05 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgDefault', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('imgProcessed', models.ImageField(blank=True, null=True, upload_to='img/')),
            ],
        ),
    ]
